language: node_js
node_js:
- 9.2.0
install:
- npm i
before_script:
- chmod +x ./scripts/deploy.sh
script:
- npm run build
- npm run unit
after_success:
- bash ./scripts/deploy.sh
env:
  global:
  - GH_USER: brfreitas
  - GH_USER_EMAIL: brunofreitas7@gmail.com
  - GH_REPO: proj-es-ifpe-2017
  - secure: NDNzzUWeYh7Rl4M9YPxhA/Etb9Je0b1ZHDu4spqaWgqFLKcZITpv1UHO/esjcsnvS9pGCKk1X5KJAFujS2/wwcgr7XHkYGDZ/JEEpBjtBoSS7uDx/jytTvwOcZW/u3SwjErVOK0BIWZY/087Wx89xzMQkCds//hUKh3blpPa/1y4vXJRiExU8XhtfQ0w+XvULBaVj/ky9hL7Wc0fWa9tBY5IpgHRZf8N+xCtGo0PdA9SL87ykJyBU5iMg91Vkg2OoGfiCxUC0bEMLaWGHL1v22+iQk61g+ZAfLEizae8fhIG+xaNvmCYfrBtdTuWRjW9WvqcRbGajwQFw9XzhsHcjJ2RuM89swqkuRRuERoQjLJZyK049WvcFIe3TyiPvTcq+ESVYm8QskVoKa3NengW7V1rWeycLcmeM3WVvmHvguY4OQQu2ZorsAnUTLIQVcJa3kiQuO5s76dR9Aj6s4t2kFmNbNisrDIUs3AoMNH7l3rY+amdM4WyQwlm6VXFMjjRztKilZy2NyQ0p/9STbQQMABuvcjcV/DGMddM9Yte9e5+zJECdbVIq1sUB4r7LbDodTSZmFS3k5TX7v/elxNwA/Ppiojc8pUdUB0IWsDef44UNwgotCQXZsRlPivffJsKo5uRzXfZsHmjtaG9umgBca7VrobEj8/EpHfe/8AdJ/k=
